# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

cookbook 'nodejs', '~> 6.0.0'
cookbook 'yarn', '~> 0.4.2'
cookbook 'postgresql', '~> 7.1.1'
cookbook 'redisio', '~> 2.7.2'
